spring:
  application:
    name: consumer1
    #MQTT配置信息
  mqtt:
    #MQTT服务地址，端口号默认11883，如果有多个，用逗号隔开
    url: tcp://192.168.31.136:25656
    #用户名
    username: test
    #密码
    password: 1234
    #客户端id(不能重复)
    client:
      id: consumer1
    #MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: t/2
server:
  port: 8081
